export const users = [
    {
        id: 1,
        name: 'Nguyen Van A',
        email: 'nguyenvana@example.com',
        age: 28,
        address: '123 Le Loi, Ho Chi Minh City',
        avatar: 'https://example.com/avatars/nguyenvana.jpg',
        isBanned: false,
        balance: 1000.50,
    },
    {
        id: 2,
        name: 'Tran Thi B',
        email: 'tranthib@example.com',
        age: 32,
        address: '456 Nguyen Trai, Hanoi',
        avatar: 'https://example.com/avatars/tranthib.jpg',
        isBanned: true,
        balance: 250.75,
    },
    {
        id: 3,
        name: 'Le Van C',
        email: 'levanc@example.com',
        age: 24,
        address: '789 Hai Ba Trung, Da Nang',
        avatar: 'https://example.com/avatars/levanc.jpg',
        isBanned: false,
        balance: 500.00,
    },
    {
        id: 4,
        name: 'Pham Thi D',
        email: 'phamthid@example.com',
        age: 29,
        address: '101 Le Duan, Can Tho',
        avatar: 'https://example.com/avatars/phamthid.jpg',
        isBanned: false,
        balance: 750.25,
    },
    {
        id: 5,
        name: 'Hoang Van E',
        email: 'hoangvane@example.com',
        age: 35,
        address: '202 Tran Hung Dao, Hue',
        avatar: 'https://example.com/avatars/hoangvane.jpg',
        isBanned: true,
        balance: 300.00,
    }
];

export const foods = 
[
    {
        id: 1,
        name: "Pho",
        description: "Traditional Vietnamese noodle soup",
        price: "$10",
        image: "pho.jpg",
    },
    {
        id: 2,
        name: "Banh Mi",
        description: "Vietnamese sandwich",
        price: "$5",
        image: "banhmi.jpg",
    },
    {
        id: 3,
        name: "Spring Rolls",
        description: "Fresh spring rolls with shrimp and vegetables",
        price: "$7",
        image: "springrolls.jpg",
    },
    {
        id: 4,
        name: "Bun Cha",
        description: "Grilled pork with noodles",
        price: "$8",
        image: "buncha.jpg",
    },
    {
        id: 5,
        name: "Goi Cuon",
        description: "Vietnamese fresh spring rolls",
        price: "$6",
        image: "goicuon.jpg",
    },
    {
        id: 6,
        name: "Com Tam",
        description: "Broken rice with grilled pork",
        price: "$9",
        image: "comtam.jpg",
    },
    {
        id: 7,
        name: "Banh Xeo",
        description: "Vietnamese savory crepe",
        price: "$7",
        image: "banhxeo.jpg",
    },
    {
        id: 8,
        name: "Ca Kho To",
        description: "Caramelized fish in clay pot",
        price: "$12",
        image: "cakhoto.jpg",
    },
    {
        id: 9,
        name: "Bun Bo Hue",
        description: "Spicy beef noodle soup",
        price: "$11",
        image: "bunbohue.jpg",
    },
    {
        id: 10,
        name: "Cha Gio",
        description: "Vietnamese fried spring rolls",
        price: "$6",
        image: "chagio.jpg",
    }
];